spring:
  cloud:
    gateway:
      routes:
        - id: audit-service
          uri: http://audit-service.egov:8080/
          predicates:
            - Path=/audit-service/**

        - id: access
          uri: http://egov-accesscontrol.egov:8080/
          predicates:
            - Path=/access/**

        - id: egov-enc-service
          uri: http://egov-enc-service.egov:8080/
          predicates:
            - Path=/egov-enc-service/**

        - id: filestore
          uri: http://egov-filestore.egov:8080/
          predicates:
            - Path=/filestore/**

        - id: egov-hrms
          uri: http://egov-hrms.egov:8080/
          predicates:
            - Path=/egov-hrms/**

        - id: egov-idgen
          uri: http://egov-idgen.egov:8080/
          predicates:
            - Path=/egov-idgen/**

        - id: egov-indexer
          uri: http://egov-indexer.egov:8080/
          predicates:
            - Path=/egov-indexer/**

        - id: localization
          uri: http://egov-localization.egov:8080/
          predicates:
            - Path=/localization/**

        - id: egov-location
          uri: http://egov-location.egov:8080/
          predicates:
            - Path=/egov-location/**

        - id: egov-mdms-service
          uri: http://egov-mdms-service.egov:8080/
          predicates:
            - Path=/egov-mdms-service/**

        - id: otp
          uri: http://egov-otp.egov:8080/
          predicates:
            - Path=/otp/**

        - id: pg-service
          uri: http://egov-pg-service.egov:8080/
          predicates:
            - Path=/pg-service/**

        - id: user
          uri: http://egov-user.egov:8080/
          predicates:
            - Path=/user/**

        - id: egov-workflow-v2
          uri: http://egov-workflow-v2.egov:8080/
          predicates:
            - Path=/egov-workflow-v2/**

        - id: pgr-services
          uri: http://pgr-services.egov:8080/
          predicates:
            - Path=/pgr-services/**

        - id: service-request
          uri: http://service-request.egov:8080/
          predicates:
            - Path=/service-request/**

        - id: user-otp
          uri: http://user-otp.egov:8080/
          predicates:
            - Path=/user-otp/**