#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: boundary_route_yaml
#          uri: http://localhost:8082
#          predicates:
#            - Path=/egov-location/location/v11/boundarys/_search
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 2
#                redis-rate-limiter.requestedTokens: 1

spring:
  cloud:
    gateway:
      routes:
        - id: boundary_route_yaml
          uri: http://localhost:8082
          predicates:
            - Path=/egov-location/location/v11/boundarys/_search
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 4

        - id: audit-service
          uri: http://audit-service.egov:8080/
          predicates:
            - Path=/audit-service/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2
                redis-rate-limiter.requestedTokens: 1

        - id: billing-service
          uri: http://billing-service.egov:8080/
          predicates:
            - Path=/billing-service/**

        - id: boundary-service
          uri: http://boundary-service.egov:8080/
          predicates:
            - Path=/boundary-service/**

        - id: whatsapp-webhook
          uri: http://chatbot.egov:8080/
          predicates:
            - Path=/whatsapp-webhook/**

        - id: collection-services
          uri: http://collection-services.egov:8080/
          predicates:
            - Path=/collection-services/**

        - id: dashboard-analytics
          uri: http://dashboard-analytics.egov:8080/
          predicates:
            - Path=/dashboard-analytics/**

        - id: egf-instrument
          uri: http://egf-instrument.egov:8080/
          predicates:
            - Path=/egf-instrument/**

        - id: egf-master
          uri: http://egf-master.egov:8080/
          predicates:
            - Path=/egf-master/**

        - id: access
          uri: http://egov-accesscontrol.egov:8080/
          predicates:
            - Path=/access/**

        - id: apportion-service
          uri: http://egov-apportion-service.egov:8080/
          predicates:
            - Path=/apportion-service/**

        - id: egov-document-uploader
          uri: http://egov-document-uploader.egov:8080/
          predicates:
            - Path=/egov-document-uploader/**

        - id: egov-enc-service
          uri: http://egov-enc-service.egov:8080/
          predicates:
            - Path=/egov-enc-service/**

        - id: filestore
          uri: http://egov-filestore.egov:8080/
          predicates:
            - Path=/filestore/**

        - id: egov-hrms
          uri: http://egov-hrms.egov:8080/
          predicates:
            - Path=/egov-hrms/**

        - id: egov-idgen
          uri: http://egov-idgen.egov:8080/
          predicates:
            - Path=/egov-idgen/**

        - id: egov-indexer
          uri: http://egov-indexer.egov:8080/
          predicates:
            - Path=/egov-indexer/**

        - id: localization
          uri: http://egov-localization.egov:8080/
          predicates:
            - Path=/localization/**

        - id: egov-location
          uri: http://egov-location.egov:8080/
          predicates:
            - Path=/egov-location/**

        - id: egov-mdms-service
          uri: http://egov-mdms-service.egov:8080/
          predicates:
            - Path=/egov-mdms-service/**

        - id: otp
          uri: http://egov-otp.egov:8080/
          predicates:
            - Path=/otp/**

        - id: egov-pdf
          uri: http://egov-pdf.egov:8080/
          predicates:
            - Path=/egov-pdf/**

        - id: pg-service
          uri: http://egov-pg-service.egov:8080/
          predicates:
            - Path=/pg-service/**

        - id: egov-searcher
          uri: http://egov-searcher.egov:8080/
          predicates:
            - Path=/egov-searcher/**

        - id: user
          uri: http://egov-user.egov:8080/
          predicates:
            - Path=/user/**

        - id: egov-user-event
          uri: http://egov-user-event.egov:8080/
          predicates:
            - Path=/egov-user-event/**

        - id: egov-workflow-v2
          uri: http://egov-workflow-v2.egov:8080/
          predicates:
            - Path=/egov-workflow-v2/**

        - id: inbox
          uri: http://inbox.egov:8080/
          predicates:
            - Path=/inbox/**

        - id: individual
          uri: http://individual.egov:8080/
          predicates:
            - Path=/individual/**

        - id: mdms-v2
          uri: http://mdms-v2.egov:8080/
          predicates:
            - Path=/mdms-v2/**

        - id: nlp-engine
          uri: http://nlp-engine.egov:8080/
          predicates:
            - Path=/nlp-engine/**

        - id: pdf-service
          uri: http://pdf-service.egov:8080/
          predicates:
            - Path=/pdf-service/**

        - id: project
          uri: http://project.egov:8080/
          predicates:
            - Path=/project/**

        - id: property-services
          uri: http://property-services.egov:8080/
          predicates:
            - Path=/property-services/**

        - id: pt-calculator-v2
          uri: http://pt-calculator-v2.egov:8080/
          predicates:
            - Path=/pt-calculator-v2/**

        - id: rainmaker-pgr
          uri: http://rainmaker-pgr.egov:8080/
          predicates:
            - Path=/rainmaker-pgr/**

        - id: report
          uri: http://report.egov:8080/
          predicates:
            - Path=/report/**

        - id: user-otp
          uri: http://user-otp.egov:8080/
          predicates:
            - Path=/user-otp/**

        - id: ws-calculator
          uri: http://ws-calculator.egov:8080/
          predicates:
            - Path=/ws-calculator/**

        - id: ws-services
          uri: http://ws-services.egov:8080/
          predicates:
            - Path=/ws-services/**

        - id: xstate-chatbot
          uri: http://xstate-chatbot.egov:8080/
          predicates:
            - Path=/xstate-chatbot/**

        - id: impel-fsm
          uri: http://impel-fsm.fsm:8080/
          predicates:
            - Path=/impel-fsm/**

        - id: impel-fsm-calculator
          uri: http://impel-fsm-calculator.fsm:8080/
          predicates:
            - Path=/impel-fsm-calculator/**

        - id: impel-inbox
          uri: http://impel-inbox.fsm:8080/
          predicates:
            - Path=/impel-inbox/**

        - id: impel-vehicle
          uri: http://impel-vehicle.fsm:8080/
          predicates:
            - Path=/impel-vehicle/**

        - id: impel-vendor
          uri: http://impel-vendor.fsm:8080/
          predicates:
            - Path=/impel-vendor/**

        - id: egov-enc-service
          uri: http://egov-enc-service.health:8080/
          predicates:
            - Path=/egov-enc-service/**

        - id: facility
          uri: http://facility.health:8080/
          predicates:
            - Path=/facility/**

        - id: hcm-bff
          uri: http://hcm-bff.health:8080/
          predicates:
            - Path=/hcm-bff/**

        - id: health-attendance
          uri: http://health-attendance.health:8080/
          predicates:
            - Path=/health-attendance/**

        - id: health-hrms
          uri: http://health-hrms.health:8080/
          predicates:
            - Path=/health-hrms/**

        - id: health-individual
          uri: http://health-individual.health:8080/
          predicates:
            - Path=/health-individual/**

        - id: health-project
          uri: http://health-project.health:8080/
          predicates:
            - Path=/health-project/**

        - id: household
          uri: http://household.health:8080/
          predicates:
            - Path=/household/**

        - id: product
          uri: http://product.health:8080/
          predicates:
            - Path=/product/**

        - id: referralmanagement
          uri: http://referralmanagement.health:8080/
          predicates:
            - Path=/referralmanagement/**

        - id: service-request
          uri: http://service-request.health:8080/
          predicates:
            - Path=/service-request/**

        - id: stock
          uri: http://stock.health:8080/
          predicates:
            - Path=/stock/**

        - id: transformer
          uri: http://transformer.health:8080/
          predicates:
            - Path=/transformer/**

        - id: digit-exchange
          uri: http://digit-exchange.ifix:8080/
          predicates:
            - Path=/digit-exchange/**

        - id: program-service
          uri: http://program-service.ifix:8080/
          predicates:
            - Path=/program-service/**

        - id: fsm
          uri: http://fsm.sanitation:8080/
          predicates:
            - Path=/fsm/**

        - id: fsm-calculator
          uri: http://fsm-calculator.sanitation:8080/
          predicates:
            - Path=/fsm-calculator/**

        - id: pqm-anomaly-finder
          uri: http://pqm-anomaly-finder.sanitation:8080/
          predicates:
            - Path=/pqm-anomaly-finder/**

        - id: pqm-service
          uri: http://pqm-service.sanitation:8080/
          predicates:
            - Path=/pqm-service/**

        - id: vehicle
          uri: http://vehicle.sanitation:8080/
          predicates:
            - Path=/vehicle/**

        - id: vendor
          uri: http://vendor.sanitation:8080/
          predicates:
            - Path=/vendor/**

        - id: bpa-calculator
          uri: http://bpa-calculator.urban:8080/
          predicates:
            - Path=/bpa-calculator/**

        - id: bpa-services
          uri: http://bpa-services.urban:8080/
          predicates:
            - Path=/bpa-services/**

        - id: echallan-calculator
          uri: http://echallan-calculator.urban:8080/
          predicates:
            - Path=/echallan-calculator/**

        - id: echallan-services
          uri: http://echallan-services.urban:8080/
          predicates:
            - Path=/echallan-services/**

        - id: firenoc-calculator
          uri: http://firenoc-calculator.urban:8080/
          predicates:
            - Path=/firenoc-calculator/**

        - id: firenoc-services
          uri: http://firenoc-services.urban:8080/
          predicates:
            - Path=/firenoc-services/**

        - id: land-services
          uri: http://land-services.urban:8080/
          predicates:
            - Path=/land-services/**

        - id: noc-services
          uri: http://noc-services.urban:8080/
          predicates:
            - Path=/noc-services/**

        - id: pgr-services
          uri: http://pgr-services.urban:8080/
          predicates:
            - Path=/pgr-services/**

        - id: property-services
          uri: http://property-services.urban:8080/
          predicates:
            - Path=/property-services/**

        - id: pt-calculator-v2
          uri: http://pt-calculator-v2.urban:8080/
          predicates:
            - Path=/pt-calculator-v2/**

        - id: pt-services-v2
          uri: http://pt-services-v2.urban:8080/
          predicates:
            - Path=/pt-services-v2/**

        - id: rainmaker-pgr
          uri: http://rainmaker-pgr.urban:8080/
          predicates:
            - Path=/rainmaker-pgr/**

        - id: sw-calculator
          uri: http://sw-calculator.urban:8080/
          predicates:
            - Path=/sw-calculator/**

        - id: sw-services
          uri: http://sw-services.urban:8080/
          predicates:
            - Path=/sw-services/**

        - id: tl-calculator
          uri: http://tl-calculator.urban:8080/
          predicates:
            - Path=/tl-calculator/**

        - id: tl-services
          uri: http://tl-services.urban:8080/
          predicates:
            - Path=/tl-services/**

        - id: urban-dashboard-analytics
          uri: http://urban-dashboard-analytics.urban:8080/
          predicates:
            - Path=/urban-dashboard-analytics/**

        - id: urban-dashboard-ingest
          uri: http://urban-dashboard-ingest.urban:8080/
          predicates:
            - Path=/urban-dashboard-ingest/**

        - id: urban-egov-indexer
          uri: http://urban-egov-indexer.urban:8080/
          predicates:
            - Path=/urban-egov-indexer/**

        - id: urban-national-dashboard-ingest
          uri: http://urban-national-dashboard-ingest.urban:8080/
          predicates:
            - Path=/urban-national-dashboard-ingest/**

        - id: ws-calculator
          uri: http://ws-calculator.urban:8080/
          predicates:
            - Path=/ws-calculator/**

        - id: ws-services
          uri: http://ws-services.urban:8080/
          predicates:
            - Path=/ws-services/**

        - id: attendance
          uri: http://attendance.works:8080/
          predicates:
            - Path=/attendance/**

        - id: bankaccount-service
          uri: http://bankaccounts.works:8080/
          predicates:
            - Path=/bankaccount-service/**

        - id: contract
          uri: http://contracts.works:8080/
          predicates:
            - Path=/contract/**

        - id: egov-bff-service
          uri: http://egov-bff-service.works:8080/
          predicates:
            - Path=/egov-bff-service/**

        - id: estimate
          uri: http://estimates.works:8080/
          predicates:
            - Path=/estimate/**

        - id: expense
          uri: http://expense.works:8080/
          predicates:
            - Path=/expense/**

        - id: expense-calculator
          uri: http://expense-calculator.works:8080/
          predicates:
            - Path=/expense-calculator/**

        - id: loi-service
          uri: http://loi-service.works:8080/
          predicates:
            - Path=/loi-service/**

        - id: measurement-registry
          uri: http://measurement-registry.works:8080/
          predicates:
            - Path=/measurement-registry/**

        - id: measurement-service
          uri: http://measurement-service.works:8080/
          predicates:
            - Path=/measurement-service/**

        - id: mukta-ifix-adapter
          uri: http://mukta-ifix-adapter.works:8080/
          predicates:
            - Path=/mukta-ifix-adapter/**

        - id: mukta-services
          uri: http://mukta-services.works:8080/
          predicates:
            - Path=/mukta-services/**

        - id: muster-roll
          uri: http://muster-roll.works:8080/
          predicates:
            - Path=/muster-roll/**

        - id: org-services
          uri: http://organisation.works:8080/
          predicates:
            - Path=/org-services/**

        - id: wms
          uri: http://works-management-service.works:8080/
          predicates:
            - Path=/wms/**
