#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: boundary_search
#          uri: http://localhost:8082
#          predicates:
#            - Path=/egov-location/location/v11/boundarys/_search
#          filters:
#            - AddRequestHeader=Hello, World