openapi: 3.0.1
info:
  title: Birth Registration Service.
  description: |
    This service provides APIs to register new births in the system.
  contact:
    name: eGovernments Foundation
    email: contacts@egovernments.org
  version: 1.0.0
servers:
  - url: /birth-services
paths:
  /v1/registration/_search:
    post:
      tags:
        - Birth Registration Application
      summary: Get the list of Birth registration applications
      description: 1. Search and get birth registration applications(s) based on defined
        search criteria. 2. In case multiple parameters are passed voter registration
        applications will be searched as an AND combination of all the parameters.
      parameters:
        - name: tenantId
          in: query
          description: Unique id for a tenant.
          required: true
          schema:
            type: string
            format: varchar
        - name: status
          in: query
          description: Search based on status.
          allowEmptyValue: true
          schema:
            type: string
        - name: ids
          in: query
          description: unique identifier of birth registration
          style: form
          explode: false
          schema:
            maxItems: 50
            type: array
            items:
              type: integer
              format: int64
        - name: applicationNumber
          in: query
          description: Unique application number for the Birth Registration Application
          schema:
            maxLength: 64
            minLength: 2
            type: string
      requestBody:
        description: Parameter to carry Request metadata in the request body
        content:
          '*/*':
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/RequestInfo'
        required: false
      responses:
        200:
          description: Birth registration applications(s) Retrived Successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BirthRegistrationRequest'
        400:
          description: Invalid input
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes'
      x-codegen-request-body-name: requestInfo
  /v1/registration/_create:
    post:
      tags:
        - Birth Registration Application
      summary: Create new Birth Registration Application
      description: "To create new birth registration applications in the system. API\
        \ supports bulk creation with max limit as defined in the Birth Registration\
        \ Request. Please note that either whole batch succeeds or fails, there's\
        \ no partial batch success. \n  \n"
      requestBody:
        description: Details for the new Birth Registration Application(s) + RequestInfo
          meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/BirthRegistrationRequest'
        required: true
      responses:
        201:
          description: ReponseInfo with Birth Registration Application(s) created
            successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BirthRegistrationResponse'
        400:
          description: Birth Registration Application(s) creation failed
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes'
      x-codegen-request-body-name: BirthRegistrationRequest
  /v1/registration/_update:
    post:
      tags:
        - Birth Registration Application
      summary: update existing Birth Registration Applications.
      description: |
        To update existing birth registration applications in the system. API supports bulk updation with max limit as defined in the birth registration Request. Please note that either whole batch succeeds or fails, there's no partial batch success.
      requestBody:
        description: Details for the new (s) + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/BirthRegistrationRequest'
        required: true
      responses:
        201:
          description: ReponseInfo with Birth Registration Application(s) updated
            sudcessfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BirthRegistrationResponse'
        400:
          description: (s) updation failed
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes'
      x-codegen-request-body-name: BirthRegistrationRequest
components:
  schemas:
    Applicant:
      description: Details of the user applying for birth registration
      allOf:
        - $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/egov-user/contracts/v1-0-0.yml#/definitions/User'
    BirthRegistrationApplication:
      required:
        - applicant
        - babyFirstName
        - babyLastName
        - doctorName
        - fatherMobileNumber
        - fatherOfApplicant
        - hospitalName
        - motherMobileNumber
        - motherOfApplicant
        - placeOfBirth
        - tenantId
        - timeOfBirth
      type: object
      properties:
        id:
          maxLength: 64
          minLength: 2
          type: string
          description: Unique Identifier of the Birth Registration Application (UUID)
          readOnly: true
        tenantId:
          maxLength: 128
          minLength: 2
          type: string
          description: Unique Identifier of ULB
        applicationNumber:
          maxLength: 128
          minLength: 2
          type: string
          description: Unique application number
          readOnly: true
        babyFirstName:
          maxLength: 128
          minLength: 2
          type: string
          description: Baby’s first name
        babyLastName:
          maxLength: 128
          minLength: 2
          type: string
          description: Baby’s last name
        fatherOfApplicant:
          maxLength: 128
          minLength: 2
          type: string
          description: Name of father
        motherOfApplicant:
          maxLength: 128
          minLength: 2
          type: string
          description: Name of mother
        fatherMobileNumber:
          maxLength: 128
          minLength: 2
          type: string
          description: Number of father
        motherMobileNumber:
          maxLength: 128
          minLength: 2
          type: string
          description: Number of mother
        doctorName:
          maxLength: 128
          minLength: 2
          type: string
          description: Name of doctor
        hospitalName:
          maxLength: 128
          minLength: 2
          type: string
          description: Name of hospital
        placeOfBirth:
          maxLength: 128
          minLength: 2
          type: string
          description: Place of birth
        timeOfBirth:
          type: integer
          description: Date of birth epoch
        address:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/Address'
        applicant:
          $ref: '#/components/schemas/Applicant'
        auditDetails:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/AuditDetails'
      description: A Object holds the basic data for a Birth Registration Application
    Workflow:
      type: object
      description: Fields related to workflow service
      properties:
        action:
          type: string
          description: Action on the application in certain
          minLength: 1
          maxLength: 64
        status:
          type: string
          description: status of the application
        comments:
          type: string
          description: Unique Identifier scrutinized number
          minLength: 1
          maxLength: 64
        documents:
          description: Attach the workflow verification documents.
          type: array
          items:
            $ref: https://raw.githubusercontent.com/egovernments/municipal-services/common-contract/docs/common-contract-v2-0-0.yml#/components/schemas/Document
    BirthRegistrationRequest:
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/RequestInfo'
        BirthRegistrationApplications:
          type: array
          description: Used for search result and create only
          items:
            $ref: '#/components/schemas/BirthRegistrationApplication'
      description: Contract class to receive request. Array of  items are used in
        case of create, whereas single  item is used for update
    BirthRegistrationResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ResponseInfo'
        BirthRegistrationApplications:
          type: array
          description: Used for search result and create only
          items:
            $ref: '#/components/schemas/BirthRegistrationApplication'
      description: Contract class to send response. Array of  items are used in case
        of search results or response for create, whereas single  item is used for
        update
x-api-id: org.egov.birth.services
x-common-path: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml
