name: Java CI Build

on:
  push:
    branches:
      - githubactions-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Maven Build
      run: mvn -B package --file pom.xml

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: build/maven/Dockerfile
        push: true
        tags: user/repo:tag
