name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, arc-runner-set-uat]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run custom scripts
      run: |
        /scripts/get_application_version.sh core-services/egov-mdms-service
        /scripts/get_folder_commit.sh core-services/egov-mdms-service

    # Add any additional steps you need here
